CREATE TABLE contracts (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DATE_CREATE DATETIME NOT NULL,
    DATE_MODIFY DATETIME NOT NULL,
    CREATED_BY INT NOT NULL,
    MODIFIED_BY INT NOT NULL,
    UF_SUMMA DECIMAL(10, 2) DEFAULT 0,
    UF_DATE_SIGN DATE,
    UF_NUMBER VARCHAR(50),
    UF_STATUS VARCHAR(50) DEFAULT 'активный',

    FOREIGN KEY (CREATED_BY) REFERENCES b_user(ID),
    FOREIGN KEY (MODIFIED_BY) REFERENCES b_user(ID),

    INDEX idx_date_create (DATE_CREATE),
    INDEX idx_status (UF_STATUS)
) ENGINE=InnoDB;